// <auto-generated />
using System;
using CompraProgramadaAcoes.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompraProgramadaAcoes.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CompraProgramadaAcoes.Domain.Entities.CestaRecomendacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataDesativacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CestasRecomendacao", (string)null);
                });

            modelBuilder.Entity("CompraProgramadaAcoes.Domain.Entities.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<DateTime>("DataAdesao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("ValorMensal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("CompraProgramadaAcoes.Domain.Entities.ContaGrafica", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NumeroConta")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.HasIndex("NumeroConta")
                        .IsUnique();

                    b.ToTable("ContasGraficas", (string)null);
                });

            modelBuilder.Entity("CompraProgramadaAcoes.Domain.Entities.Cotacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataPregao")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PrecoAbertura")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PrecoFechamento")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PrecoMaximo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PrecoMinimo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("DataPregao", "Ticker")
                        .IsUnique();

                    b.ToTable("Cotacoes", (string)null);
                });

            modelBuilder.Entity("CompraProgramadaAcoes.Domain.Entities.CotacaoB3", b =>
                {
                    b.Property<DateTime>("DataPregao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Ticker")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("CodigoBDI")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("NomeEmpresa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("PrecoAbertura")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PrecoFechamento")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PrecoMaximo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PrecoMedio")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PrecoMinimo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<long>("QuantidadeNegociada")
                        .HasColumnType("bigint");

                    b.Property<int>("TipoMercado")
                        .HasColumnType("int");

                    b.Property<decimal>("VolumeNegociado")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DataPregao", "Ticker");

                    b.ToTable("CotacoesB3", (string)null);
                });

            modelBuilder.Entity("CompraProgramadaAcoes.Domain.Entities.Custodia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ContaGraficaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataUltimaAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PrecoMedio")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("ContaGraficaId", "Ticker")
                        .IsUnique();

                    b.ToTable("Custodias", (string)null);
                });

            modelBuilder.Entity("CompraProgramadaAcoes.Domain.Entities.Distribuicao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CustodiaFilhoteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataDistribuicao")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("OrdemCompraId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("CustodiaFilhoteId");

                    b.HasIndex("OrdemCompraId");

                    b.ToTable("Distribuicoes", (string)null);
                });

            modelBuilder.Entity("CompraProgramadaAcoes.Domain.Entities.EventoIR", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataEvento")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("PublicadoKafka")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("ValorBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorIR")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("EventosIR", (string)null);
                });

            modelBuilder.Entity("CompraProgramadaAcoes.Domain.Entities.HistoricoValorMensal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("ValorAnterior")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorNovo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("HistoricoValoresMensais", (string)null);
                });

            modelBuilder.Entity("CompraProgramadaAcoes.Domain.Entities.ItemCesta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CestaId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Percentual")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("CestaId", "Ticker")
                        .IsUnique();

                    b.ToTable("ItensCesta", (string)null);
                });

            modelBuilder.Entity("CompraProgramadaAcoes.Domain.Entities.OrdemCompra", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ContaMasterId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataExecucao")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("TipoMercado")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.HasKey("Id");

                    b.HasIndex("ContaMasterId");

                    b.ToTable("OrdensCompra", (string)null);
                });

            modelBuilder.Entity("CompraProgramadaAcoes.Domain.Entities.Rebalanceamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataRebalanceamento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TickerComprado")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("TickerVendido")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<decimal>("ValorVenda")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Rebalanceamentos", (string)null);
                });

            modelBuilder.Entity("CompraProgramadaAcoes.Domain.Entities.Venda", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("CustoAquisicao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DataOperacao")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("IrRetido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Lucro")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("ValorVenda")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Vendas", (string)null);
                });

            modelBuilder.Entity("CompraProgramadaAcoes.Domain.Entities.ContaGrafica", b =>
                {
                    b.HasOne("CompraProgramadaAcoes.Domain.Entities.Cliente", "Cliente")
                        .WithOne("ContaGrafica")
                        .HasForeignKey("CompraProgramadaAcoes.Domain.Entities.ContaGrafica", "ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Conta_Cliente");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("CompraProgramadaAcoes.Domain.Entities.Custodia", b =>
                {
                    b.HasOne("CompraProgramadaAcoes.Domain.Entities.ContaGrafica", "ContaGrafica")
                        .WithMany("Custodias")
                        .HasForeignKey("ContaGraficaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Custodia_Conta");

                    b.Navigation("ContaGrafica");
                });

            modelBuilder.Entity("CompraProgramadaAcoes.Domain.Entities.Distribuicao", b =>
                {
                    b.HasOne("CompraProgramadaAcoes.Domain.Entities.Custodia", "CustodiaFilhote")
                        .WithMany()
                        .HasForeignKey("CustodiaFilhoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Distribuicao_Custodia");

                    b.HasOne("CompraProgramadaAcoes.Domain.Entities.OrdemCompra", "OrdemCompra")
                        .WithMany("Distribuicoes")
                        .HasForeignKey("OrdemCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Distribuicao_OrdemCompra");

                    b.Navigation("CustodiaFilhote");

                    b.Navigation("OrdemCompra");
                });

            modelBuilder.Entity("CompraProgramadaAcoes.Domain.Entities.EventoIR", b =>
                {
                    b.HasOne("CompraProgramadaAcoes.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EventoIR_Cliente");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("CompraProgramadaAcoes.Domain.Entities.HistoricoValorMensal", b =>
                {
                    b.HasOne("CompraProgramadaAcoes.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_HistoricoValorMensal_Cliente");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("CompraProgramadaAcoes.Domain.Entities.ItemCesta", b =>
                {
                    b.HasOne("CompraProgramadaAcoes.Domain.Entities.CestaRecomendacao", "Cesta")
                        .WithMany("Itens")
                        .HasForeignKey("CestaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ItemCesta_Cesta");

                    b.Navigation("Cesta");
                });

            modelBuilder.Entity("CompraProgramadaAcoes.Domain.Entities.OrdemCompra", b =>
                {
                    b.HasOne("CompraProgramadaAcoes.Domain.Entities.ContaGrafica", "ContaMaster")
                        .WithMany("OrdensCompra")
                        .HasForeignKey("ContaMasterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_OrdemCompra_ContaMaster");

                    b.Navigation("ContaMaster");
                });

            modelBuilder.Entity("CompraProgramadaAcoes.Domain.Entities.Rebalanceamento", b =>
                {
                    b.HasOne("CompraProgramadaAcoes.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Rebalanceamento_Cliente");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("CompraProgramadaAcoes.Domain.Entities.CestaRecomendacao", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("CompraProgramadaAcoes.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("ContaGrafica")
                        .IsRequired();
                });

            modelBuilder.Entity("CompraProgramadaAcoes.Domain.Entities.ContaGrafica", b =>
                {
                    b.Navigation("Custodias");

                    b.Navigation("OrdensCompra");
                });

            modelBuilder.Entity("CompraProgramadaAcoes.Domain.Entities.OrdemCompra", b =>
                {
                    b.Navigation("Distribuicoes");
                });
#pragma warning restore 612, 618
        }
    }
}
